# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
# Bao gồm các stages để kiểm tra bảo mật và đồng bộ repo
stages:
  - test
  - sync

# Include SAST template
include:
  - template: Security/SAST.gitlab-ci.yml

# Job SAST kiểm tra bảo mật
sast:
  stage: test

# Job đồng bộ hai repo
sync_repo:
  stage: sync
  script:
    - git remote add second-repo https://lnl2002:${GITHUB_TOKEN}@github.com/lnl2002/deploy-recruit-me.git
    - git fetch second-repo
    - git push second-repo main --force
  only:
    - main
