# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
# Bao gồm các stages để kiểm tra bảo mật và đồng bộ repo
stages:
  - test
  - sync

# Include SAST template
include:
  - template: Security/SAST.gitlab-ci.yml
variables:
  GITLAB_ADVANCED_SAST_ENABLED: 'true'
  
# Job SAST kiểm tra bảo mật
sast:
  stage: test

sync_repo:
  stage: sync
  script:
    - git checkout -b main || git checkout main
    - echo "${GITHUB_TOKEN}"
    # Thêm remote repository GitHub
    - git remote add second-repo https://lnl2002:${GITHUB_TOKEN}@github.com/lnl2002/deploy-recruit-me.git
    
    # Đẩy code từ GitLab lên GitHub, sử dụng nhánh `main`
    - git push second-repo main --force
    
  only:
    - main

# Include GitLab CI/CD secret tokens for authentication
variables:
  GIT_STRATEGY: fetch
